//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLinkText {
            get {
                return ResourceManager.GetString("AboutLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Manager is an application that manages access to Amgen’s file shares instead of requestors submitting a Service Request to Service-Now.  It allows file share owners and access requestors a self-service option for this activity.&lt;br /&gt;&lt;br /&gt;
        ///
        ///It is a web-based application so you can access it from your web browser at &lt;a href=&quot;http:\\sharemanager.amgen.com&quot;&gt;http:\\sharemanager.amgen.com&lt;/a&gt;. Share Manager supports access updates to a file share or a share sub-folder. &lt;br /&gt;&lt;br /&gt;
        ///
        ///The Share Manager a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutPageContent {
            get {
                return ResourceManager.GetString("AboutPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Action Required].
        /// </summary>
        public static string ActionRequired {
            get {
                return ResourceManager.GetString("ActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Share.
        /// </summary>
        public static string AddNewShare {
            get {
                return ResourceManager.GetString("AddNewShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SysMsg for Developer.
        /// </summary>
        public static string AdHelperErrorMsg {
            get {
                return ResourceManager.GetString("AdHelperErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Modification.
        /// </summary>
        public static string ADModifyFailure {
            get {
                return ResourceManager.GetString("ADModifyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are an Share Administrator, click below to go to the Share Administration area and Add new aliases to Share Manager or manage existing aliases..
        /// </summary>
        public static string AliasAdminContent {
            get {
                return ResourceManager.GetString("AliasAdminContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Alias Administration.
        /// </summary>
        public static string AliasAdminHeading {
            get {
                return ResourceManager.GetString("AliasAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-colon delimited list of Windows login credentials.
        /// </summary>
        public static string AliasesList {
            get {
                return ResourceManager.GetString("AliasesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Aliases.
        /// </summary>
        public static string AliasListHeading {
            get {
                return ResourceManager.GetString("AliasListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and either Approve or Deny this request..
        /// </summary>
        public static string AndApproveOrDenyRequest {
            get {
                return ResourceManager.GetString("AndApproveOrDenyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Manager.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve or Deny Request.
        /// </summary>
        public static string ApproveDenyRequestPageHeading {
            get {
                return ResourceManager.GetString("ApproveDenyRequestPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Request.
        /// </summary>
        public static string ApproveRequest {
            get {
                return ResourceManager.GetString("ApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a decision before submit the request.
        /// </summary>
        public static string ApproverNoDecision {
            get {
                return ResourceManager.GetString("ApproverNoDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to request access for a user who already has the access you requested..
        /// </summary>
        public static string AttemptAddUserWhoAlreadyHasAccess {
            get {
                return ResourceManager.GetString("AttemptAddUserWhoAlreadyHasAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No share owner is identified, thus access request is not allowed..
        /// </summary>
        public static string AttemptEmptyOwnerRequest {
            get {
                return ResourceManager.GetString("AttemptEmptyOwnerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request you just submitted was invalid. One of the following conditions caused the error:.
        /// </summary>
        public static string AttemptError {
            get {
                return ResourceManager.GetString("AttemptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to create an identical request..
        /// </summary>
        public static string AttemptIdenticalRequest {
            get {
                return ResourceManager.GetString("AttemptIdenticalRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name is not valid or not in the same domain as the share..
        /// </summary>
        public static string AttemptInvalidGroup {
            get {
                return ResourceManager.GetString("AttemptInvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User alias is not valid..
        /// </summary>
        public static string AttemptInvalidUser {
            get {
                return ResourceManager.GetString("AttemptInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You attempted to request removal for a user who doesn&apos;t have the permissions you tried to remove..
        /// </summary>
        public static string AttemptRemoveForNonMember {
            get {
                return ResourceManager.GetString("AttemptRemoveForNonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to remove the last share owner..
        /// </summary>
        public static string AttemptRemoveLastOnwer {
            get {
                return ResourceManager.GetString("AttemptRemoveLastOnwer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to My Requests.
        /// </summary>
        public static string BackToMyRequests {
            get {
                return ResourceManager.GetString("BackToMyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Share Details.
        /// </summary>
        public static string BackToShareDetails {
            get {
                return ResourceManager.GetString("BackToShareDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Shares List.
        /// </summary>
        public static string BackToSharesList {
            get {
                return ResourceManager.GetString("BackToSharesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share and Storage Administrator.
        /// </summary>
        public static string BothAdmin {
            get {
                return ResourceManager.GetString("BothAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Available Shares.
        /// </summary>
        public static string BrowseAvailableShares {
            get {
                return ResourceManager.GetString("BrowseAvailableShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request has been cancelled by the system due to inactivity.  If you still need this request to be fulfilled, please submit a new request in Share Manager AND follow up with approvers so that they take action as needed.  Note: No other parties but you are responsible for ensuring approver&apos;s action is taken..
        /// </summary>
        public static string CancelledRequestMessage {
            get {
                return ResourceManager.GetString("CancelledRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Request.
        /// </summary>
        public static string CancelRequest {
            get {
                return ResourceManager.GetString("CancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Preferred Language.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search.
        /// </summary>
        public static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string ClosedBy {
            get {
                return ResourceManager.GetString("ClosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMDB CI.
        /// </summary>
        public static string CmdbCi {
            get {
                return ResourceManager.GetString("CmdbCi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMDB CI is required.
        /// </summary>
        public static string CmdbCiRequired {
            get {
                return ResourceManager.GetString("CmdbCiRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Requests.
        /// </summary>
        public static string CompletedRequests {
            get {
                return ResourceManager.GetString("CompletedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback &amp; Contact.
        /// </summary>
        public static string ContactLinkText {
            get {
                return ResourceManager.GetString("ContactLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Manager team is working very hard to ensure quality of the application, service and experience for our customers.&lt;br /&gt;&lt;br /&gt;
        ///
        ///Site Contact information and a Questions submission form are located on the left panel of the &lt;a href=&quot;https://myteams.amgen.com/sites/ahs-storage/sharemanager/Pages/Home.aspx&quot;&gt;Share Manager Help Center&lt;/a&gt;. &lt;br /&gt;&lt;br /&gt;
        ///
        ///Specific Questions:&lt;br /&gt;
        ///&lt;UL&gt;
        ///&lt;li&gt;I can&apos;t find the file share I own or need access to. Submit a request &lt;a href=&quot;https://myteams.amgen.com/sites/AHS-S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContactPageContent {
            get {
                return ResourceManager.GetString("ContactPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHS - Storage and Backup.
        /// </summary>
        public static string CopyRightBy {
            get {
                return ResourceManager.GetString("CopyRightBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatedOnDateTime {
            get {
                return ResourceManager.GetString("CreatedOnDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Access Request.
        /// </summary>
        public static string CreateNewRequestButton {
            get {
                return ResourceManager.GetString("CreateNewRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  day(s)..
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Denied.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny Request.
        /// </summary>
        public static string DenyRequest {
            get {
                return ResourceManager.GetString("DenyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the latest information about this share and to check your permissions, .
        /// </summary>
        public static string EmailClosingP1 {
            get {
                return ResourceManager.GetString("EmailClosingP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you have any problems with your permissions, please file a Service Request in &lt;a href=&quot;https://amgen.service-now.com/navpage.do&quot;&gt;Service-Now&lt;/a&gt; and choose .
        /// </summary>
        public static string EmailClosingP2 {
            get {
                return ResourceManager.GetString("EmailClosingP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as your resolver group.&lt;/br&gt;&lt;/br&gt;&lt;/p&gt;&lt;p&gt;Thank you,&lt;/br&gt;The Share Manager Team&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string EmailClosingP3 {
            get {
                return ResourceManager.GetString("EmailClosingP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reboot your computer for latest access to take effective..
        /// </summary>
        public static string EmailClosingRestart {
            get {
                return ResourceManager.GetString("EmailClosingRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ENTER key is disabled on this page..
        /// </summary>
        public static string EnterKeyDisabled {
            get {
                return ResourceManager.GetString("EnterKeyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by name:.
        /// </summary>
        public static string FindByName {
            get {
                return ResourceManager.GetString("FindByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string ForLowerCase {
            get {
                return ResourceManager.GetString("ForLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Area.
        /// </summary>
        public static string FunctionName {
            get {
                return ResourceManager.GetString("FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the self-service Share Manager application.  This application can be used by anyone at Amgen to:&lt;br /&gt;
        ///- Request access to a network file share or shared folder&lt;br /&gt;
        ///- See who owns a particular file share or shared folder&lt;br /&gt;
        ///And for File Share Owners to:&lt;br /&gt;
        ///- Manage access to the file shares and folders you own..
        /// </summary>
        public static string GettingStartedContent {
            get {
                return ResourceManager.GetString("GettingStartedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string GettingStartedHeading {
            get {
                return ResourceManager.GetString("GettingStartedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner/Approver.
        /// </summary>
        public static string GK {
            get {
                return ResourceManager.GetString("GK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeLinkText {
            get {
                return ResourceManager.GetString("HomeLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please &lt;b&gt;&lt;u&gt;take action on this request immediately&lt;/u&gt;&lt;/b&gt; as this is the only automated notification you will receive from the Share Manager application.&lt;br/&gt;[Note to the Requestor: It is your responsibility to follow-up directly with the Owner as needed.].
        /// </summary>
        public static string ImmediateActionRequired {
            get {
                return ResourceManager.GetString("ImmediateActionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Service.
        /// </summary>
        public static string InService {
            get {
                return ResourceManager.GetString("InService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a File Share Registry Share?.
        /// </summary>
        public static string IsFsrShare {
            get {
                return ResourceManager.GetString("IsFsrShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified On.
        /// </summary>
        public static string ModifiedOnDateTime {
            get {
                return ResourceManager.GetString("ModifiedOnDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For More Information:.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Please note that the Share Manager is the new application for file share access management. Instead of requestors submitting a Service Catalog Request in Service-Now, this application allows share owners and users a self-service option. Click &lt;a href=&quot;http://sharemanager.amgen.com&quot;&gt;here&lt;/a&gt; to access Share Manager and &lt;a href=&quot;https://myteams.amgen.com/sites/AHS-Storage/sharemanager/Pages/Home.aspx&quot;&gt;here&lt;/a&gt; to access the Share Manager Help Center.&lt;/li&gt;
        ///&lt;li&gt;Learn how to use the Share Manager appl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MoreInfoContent {
            get {
                return ResourceManager.GetString("MoreInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string MyRequests {
            get {
                return ResourceManager.GetString("MyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change.
        /// </summary>
        public static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change (No Modify) Share Members.
        /// </summary>
        public static string NcMembers {
            get {
                return ResourceManager.GetString("NcMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change Group.
        /// </summary>
        public static string NoChangeGroup {
            get {
                return ResourceManager.GetString("NoChangeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no completed or failed requests for this share..
        /// </summary>
        public static string NoCompletedRequestsForShare {
            get {
                return ResourceManager.GetString("NoCompletedRequestsForShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO, RW or NC group is not configured for this share thus access requet is not allowed.
        /// </summary>
        public static string NoGroupConfigured {
            get {
                return ResourceManager.GetString("NoGroupConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You current have NO open requests either submitted by your or submitted on your behalf..
        /// </summary>
        public static string NoOpenRequestContent {
            get {
                return ResourceManager.GetString("NoOpenRequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently don&apos;t have any open permission requests..
        /// </summary>
        public static string NoRequestCountContent {
            get {
                return ResourceManager.GetString("NoRequestCountContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Open Request.
        /// </summary>
        public static string NoRequestCountHeading {
            get {
                return ResourceManager.GetString("NoRequestCountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not finding what you are looking for? Submit a request &lt;a href=&quot;https://myteams.amgen.com/sites/AHS-Storage/sharemanager/Lists/Add%20Shares%20to%20Share%20Manager/AllItems.aspx&quot;&gt;here&lt;/a&gt; to have it added..
        /// </summary>
        public static string NotFineYourShare {
            get {
                return ResourceManager.GetString("NotFineYourShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only One Alias per Request is supported at this time..
        /// </summary>
        public static string OneAlias {
            get {
                return ResourceManager.GetString("OneAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 150 characters.
        /// </summary>
        public static string OneFiftyLength {
            get {
                return ResourceManager.GetString("OneFiftyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only One Group Name per Request is supported at this time. Example name, test-sharemgmt_nestedgroup..
        /// </summary>
        public static string OneGroup {
            get {
                return ResourceManager.GetString("OneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 100 characters.
        /// </summary>
        public static string OneHundredLength {
            get {
                return ResourceManager.GetString("OneHundredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the following requests that you have submitted or were submitted on your behalf..
        /// </summary>
        public static string OpenRequestContent {
            get {
                return ResourceManager.GetString("OpenRequestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string OpenRequestCountContent1 {
            get {
                return ResourceManager.GetString("OpenRequestCountContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request(s) pending. .
        /// </summary>
        public static string OpenRequestCountContent2 {
            get {
                return ResourceManager.GetString("OpenRequestCountContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by User Alias.
        /// </summary>
        public static string OpenRequestCountHeading {
            get {
                return ResourceManager.GetString("OpenRequestCountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See My Requests.
        /// </summary>
        public static string OpenRequestLink {
            get {
                return ResourceManager.GetString("OpenRequestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Requests.
        /// </summary>
        public static string OpenRequestsHeading {
            get {
                return ResourceManager.GetString("OpenRequestsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Unit.
        /// </summary>
        public static string OrganizationalUnit {
            get {
                return ResourceManager.GetString("OrganizationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Unit is required.
        /// </summary>
        public static string OrganizationalUnitRequired {
            get {
                return ResourceManager.GetString("OrganizationalUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU (Resolver Group - Domain).
        /// </summary>
        public static string OuSelectList {
            get {
                return ResourceManager.GetString("OuSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service.
        /// </summary>
        public static string OutOfService {
            get {
                return ResourceManager.GetString("OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Group.
        /// </summary>
        public static string OwnerGroup {
            get {
                return ResourceManager.GetString("OwnerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Group is required.
        /// </summary>
        public static string OwnerGroupRequired {
            get {
                return ResourceManager.GetString("OwnerGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Owners/ Approvers.
        /// </summary>
        public static string OwnersMembers {
            get {
                return ResourceManager.GetString("OwnersMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Share.
        /// </summary>
        public static string ParentShare {
            get {
                return ResourceManager.GetString("ParentShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Requested.
        /// </summary>
        public static string PermissionType {
            get {
                return ResourceManager.GetString("PermissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share owners please click this link:.
        /// </summary>
        public static string PleaseGoTo {
            get {
                return ResourceManager.GetString("PleaseGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Share.
        /// </summary>
        public static string PrimaryCifsShare {
            get {
                return ResourceManager.GetString("PrimaryCifsShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only Group.
        /// </summary>
        public static string ReadOnlyGroup {
            get {
                return ResourceManager.GetString("ReadOnlyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only Group is required.
        /// </summary>
        public static string ReadOnlyGroupRequired {
            get {
                return ResourceManager.GetString("ReadOnlyGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/Write Group.
        /// </summary>
        public static string ReadWriteGroup {
            get {
                return ResourceManager.GetString("ReadWriteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/Write Security Group is required.
        /// </summary>
        public static string ReadWriteGroupRequired {
            get {
                return ResourceManager.GetString("ReadWriteGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take action on this request immediately.  This request will be closed in .
        /// </summary>
        public static string ReminderImmediateActionRequired1 {
            get {
                return ResourceManager.GetString("ReminderImmediateActionRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Note to the Requestor: It is your responsibility to follow-up directly with the Owner as needed.].
        /// </summary>
        public static string ReminderImmediateActionRequired2 {
            get {
                return ResourceManager.GetString("ReminderImmediateActionRequired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Reminder) Approval/Denial Pending for Access Request to.
        /// </summary>
        public static string ReminderRequestPending {
            get {
                return ResourceManager.GetString("ReminderRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Notify Approvers.
        /// </summary>
        public static string ReNotify {
            get {
                return ResourceManager.GetString("ReNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification of your request has been resent to approvers. Please check your email inbox..
        /// </summary>
        public static string ReNotifyConfirmed {
            get {
                return ResourceManager.GetString("ReNotifyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification of your request CAN NOT been resent to approvers. Please contact ShareManager team for help..
        /// </summary>
        public static string ReNotifyNotConfirmed {
            get {
                return ResourceManager.GetString("ReNotifyNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Access.
        /// </summary>
        public static string RequestAccess {
            get {
                return ResourceManager.GetString("RequestAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Request Notification Sent On.
        /// </summary>
        public static string RequestApprovalNotificationTimeStamp {
            get {
                return ResourceManager.GetString("RequestApprovalNotificationTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve/Deny.
        /// </summary>
        public static string RequestApprovalStatus {
            get {
                return ResourceManager.GetString("RequestApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approved.
        /// </summary>
        public static string RequestApproved {
            get {
                return ResourceManager.GetString("RequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Completed On.
        /// </summary>
        public static string RequestClosedOnDateTime {
            get {
                return ResourceManager.GetString("RequestClosedOnDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Completed.
        /// </summary>
        public static string RequestCompleted {
            get {
                return ResourceManager.GetString("RequestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Request was completed:.
        /// </summary>
        public static string RequestCompletedEmail {
            get {
                return ResourceManager.GetString("RequestCompletedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Open Requests.
        /// </summary>
        public static string RequestCountHeading {
            get {
                return ResourceManager.GetString("RequestCountHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Denied.
        /// </summary>
        public static string RequestDenied {
            get {
                return ResourceManager.GetString("RequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By User Alias.
        /// </summary>
        public static string RequestedByUserAlias {
            get {
                return ResourceManager.GetString("RequestedByUserAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Submitted By.
        /// </summary>
        public static string RequestedByUserName {
            get {
                return ResourceManager.GetString("RequestedByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested for User Alias.
        /// </summary>
        public static string RequestedForUserAlias {
            get {
                return ResourceManager.GetString("RequestedForUserAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested For.
        /// </summary>
        public static string RequestedForUserName {
            get {
                return ResourceManager.GetString("RequestedForUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the Owner/Gatekeeper of the below listed Network Shared Folder (File Share).  A request  was submitted in the Share Manager* application is pending your approval and cannot proceed until you take action..
        /// </summary>
        public static string RequestEmailBrief {
            get {
                return ResourceManager.GetString("RequestEmailBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Justification.
        /// </summary>
        public static string RequestJustification {
            get {
                return ResourceManager.GetString("RequestJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Request Justification is Required.
        /// </summary>
        public static string RequestJustificationRequired {
            get {
                return ResourceManager.GetString("RequestJustificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Request has been made:.
        /// </summary>
        public static string RequestMade {
            get {
                return ResourceManager.GetString("RequestMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Submitted On.
        /// </summary>
        public static string RequestOpenedOnDateTime {
            get {
                return ResourceManager.GetString("RequestOpenedOnDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval/Denial Pending for Access Request to.
        /// </summary>
        public static string RequestPending {
            get {
                return ResourceManager.GetString("RequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver Comments.
        /// </summary>
        public static string RequestStatusMsg {
            get {
                return ResourceManager.GetString("RequestStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Remove.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver Group.
        /// </summary>
        public static string ResolverGroup {
            get {
                return ResourceManager.GetString("ResolverGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver Group is required.
        /// </summary>
        public static string ResolverGroupRequired {
            get {
                return ResourceManager.GetString("ResolverGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retired.
        /// </summary>
        public static string Retired {
            get {
                return ResourceManager.GetString("Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only Users.
        /// </summary>
        public static string RoMembers {
            get {
                return ResourceManager.GetString("RoMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/Write.
        /// </summary>
        public static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/Write Users.
        /// </summary>
        public static string RwMembers {
            get {
                return ResourceManager.GetString("RwMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by (Name, UNC Path, or CMDB CI):.
        /// </summary>
        public static string SearchByNameCiOrPath {
            get {
                return ResourceManager.GetString("SearchByNameCiOrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Share/Alias.
        /// </summary>
        public static string SecondaryCifsShare {
            get {
                return ResourceManager.GetString("SecondaryCifsShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Group.
        /// </summary>
        public static string SecurityGroup {
            get {
                return ResourceManager.GetString("SecurityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Group Members.
        /// </summary>
        public static string SecurityGroupMembers {
            get {
                return ResourceManager.GetString("SecurityGroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select an Item --.
        /// </summary>
        public static string SelectListNull {
            get {
                return ResourceManager.GetString("SelectListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 75 characters.
        /// </summary>
        public static string SeventyFiveLength {
            get {
                return ResourceManager.GetString("SeventyFiveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Administrator.
        /// </summary>
        public static string ShareAdmin {
            get {
                return ResourceManager.GetString("ShareAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Administration List.
        /// </summary>
        public static string ShareAdminIndexPageTitle {
            get {
                return ResourceManager.GetString("ShareAdminIndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please note: the user list may not reflect complete user access list. Before using this information for any auditing purpose, please contact IS-Storage and confirm..
        /// </summary>
        public static string ShareDetailDisclaimer {
            get {
                return ResourceManager.GetString("ShareDetailDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Details.
        /// </summary>
        public static string ShareDetails {
            get {
                return ResourceManager.GetString("ShareDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Domain.
        /// </summary>
        public static string ShareDomain {
            get {
                return ResourceManager.GetString("ShareDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Name.
        /// </summary>
        public static string ShareName {
            get {
                return ResourceManager.GetString("ShareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Name is required.
        /// </summary>
        public static string ShareNameRequired {
            get {
                return ResourceManager.GetString("ShareNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string ShareOwner {
            get {
                return ResourceManager.GetString("ShareOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Cost Center.
        /// </summary>
        public static string ShareOwnerCostCenter {
            get {
                return ResourceManager.GetString("ShareOwnerCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Cost Center is required.
        /// </summary>
        public static string ShareOwnerCostCenterRequired {
            get {
                return ResourceManager.GetString("ShareOwnerCostCenterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Functional Area.
        /// </summary>
        public static string ShareOwnerFunctionalArea {
            get {
                return ResourceManager.GetString("ShareOwnerFunctionalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Functional Area is required.
        /// </summary>
        public static string ShareOwnerFunctionalAreaRequired {
            get {
                return ResourceManager.GetString("ShareOwnerFunctionalAreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share owner group is requried.
        /// </summary>
        public static string ShareOwnerGroupRequired {
            get {
                return ResourceManager.GetString("ShareOwnerGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares List.
        /// </summary>
        public static string SharesList {
            get {
                return ResourceManager.GetString("SharesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share UNC path is required.
        /// </summary>
        public static string ShareUNCPathsRequired {
            get {
                return ResourceManager.GetString("ShareUNCPathsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Details and Access Requests.
        /// </summary>
        public static string ShareUserDetailsPageHeader {
            get {
                return ResourceManager.GetString("ShareUserDetailsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll down to view current Owners and users with access as well as Open requests and Completed requests..
        /// </summary>
        public static string ShareUserDetailsPageTopContent {
            get {
                return ResourceManager.GetString("ShareUserDetailsPageTopContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For all Amgen users, view the list of network file shares or shared folders that are being managed by this application.&lt;br /&gt;
        ///For share owners, find the shares you manage and approve or deny permission requests.&lt;br /&gt;
        ///If you do not see a particular file share or shared folder listed, please request it to be added  &lt;a href=&quot;https://myteams.amgen.com/sites/AHS-Storage/sharemanager/Lists/Add%20Shares%20to%20Share%20Manager/AllItems.aspx&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        public static string ShareUsersContent {
            get {
                return ResourceManager.GetString("ShareUsersContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network File Shares.
        /// </summary>
        public static string ShareUsersHeading {
            get {
                return ResourceManager.GetString("ShareUsersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Administrator.
        /// </summary>
        public static string SiteAdmin {
            get {
                return ResourceManager.GetString("SiteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 65 characters.
        /// </summary>
        public static string SixtyFourLength {
            get {
                return ResourceManager.GetString("SixtyFourLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are an Share Administrator, click below to go to the Share Administration area and Add new shares to Share Manager or manage existing shares..
        /// </summary>
        public static string SmbAdminContent {
            get {
                return ResourceManager.GetString("SmbAdminContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Administration.
        /// </summary>
        public static string SmbAdminHeading {
            get {
                return ResourceManager.GetString("SmbAdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network File Shares and Folders.
        /// </summary>
        public static string SmbShare {
            get {
                return ResourceManager.GetString("SmbShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network File Shares.
        /// </summary>
        public static string SmbShareListHeading {
            get {
                return ResourceManager.GetString("SmbShareListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Requests for this Share.
        /// </summary>
        public static string SmbShareOpenRequests {
            get {
                return ResourceManager.GetString("SmbShareOpenRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMB Shares Permissions Page.
        /// </summary>
        public static string SmbSharePermListPageHeader {
            get {
                return ResourceManager.GetString("SmbSharePermListPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status User Notification.
        /// </summary>
        public static string StatusNotificationTextBox {
            get {
                return ResourceManager.GetString("StatusNotificationTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to notify the user as to why the request was denied, use the text box below:.
        /// </summary>
        public static string StatusNotificationTextBoxExplanation {
            get {
                return ResourceManager.GetString("StatusNotificationTextBoxExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Administrator.
        /// </summary>
        public static string StorageAdmin {
            get {
                return ResourceManager.GetString("StorageAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Request.
        /// </summary>
        public static string SubmitRequest {
            get {
                return ResourceManager.GetString("SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 1024 characters.
        /// </summary>
        public static string TenTwentyFourLength {
            get {
                return ResourceManager.GetString("TenTwentyFourLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you,&lt;/br&gt;The Share Manager Team.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Shares List.
        /// </summary>
        public static string ToSharesList {
            get {
                return ResourceManager.GetString("ToSharesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 25 characters.
        /// </summary>
        public static string TwentyFiveLength {
            get {
                return ResourceManager.GetString("TwentyFiveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 250 characters.
        /// </summary>
        public static string TwoFiftyLength {
            get {
                return ResourceManager.GetString("TwoFiftyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Path.
        /// </summary>
        public static string UncPath {
            get {
                return ResourceManager.GetString("UncPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access (UNC) Path is required.
        /// </summary>
        public static string UncPathRequired {
            get {
                return ResourceManager.GetString("UncPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown Item.
        /// </summary>
        public static string UnknownItem {
            get {
                return ResourceManager.GetString("UnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To.
        /// </summary>
        public static string UseLinkText {
            get {
                return ResourceManager.GetString("UseLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an share owner, you want to approve an access request:.
        /// </summary>
        public static string UsePageApproveAccess {
            get {
                return ResourceManager.GetString("UsePageApproveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is content.
        /// </summary>
        public static string UsePageContent {
            get {
                return ResourceManager.GetString("UsePageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows you how to: &lt;br /&gt;
        ///- Submit an access request if you are an Amgen user&lt;br /&gt;
        ///- Approve an access request if you are an approver &lt;br /&gt;
        ///For a request to &lt;b&gt;change ownership&lt;/b&gt;, please use &lt;a href=&quot;https://amgen.service-now.com/&quot;&gt;Service-Now&lt;/a&gt;. &lt;br/&gt;For complete instructions, please see the &lt;a href=&quot;https://myteams.amgen.com/sites/AHS-Storage/sharemanager/Shared%20Documents/Share%20Manager%20Quick%20Reference%20Guide.pdf&quot;&gt;Share Manager Quick Reference Guide&lt;/a&gt;..
        /// </summary>
        public static string UsePageReference {
            get {
                return ResourceManager.GetString("UsePageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an Amgen user, you want to request access to a share:.
        /// </summary>
        public static string UsePageRequestAccess {
            get {
                return ResourceManager.GetString("UsePageRequestAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Alias (Windows Login).
        /// </summary>
        public static string UserAlias {
            get {
                return ResourceManager.GetString("UserAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Alias is required.
        /// </summary>
        public static string UserAliasRequired {
            get {
                return ResourceManager.GetString("UserAliasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or Security Group.
        /// </summary>
        public static string UserOrGroup {
            get {
                return ResourceManager.GetString("UserOrGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Share Details.
        /// </summary>
        public static string ViewShareDetails {
            get {
                return ResourceManager.GetString("ViewShareDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeHeading {
            get {
                return ResourceManager.GetString("WelcomeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What You Need to Do:.
        /// </summary>
        public static string WhatToDo {
            get {
                return ResourceManager.GetString("WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What You Need to Know (Request Details).
        /// </summary>
        public static string WhatToKnow {
            get {
                return ResourceManager.GetString("WhatToKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can Login Below to View or Post a Message to our AHS - Storage and Backup Yammer Group. If you are already logged in. You should see our AHS - Storage and Backup Yammer feed..
        /// </summary>
        public static string YammerContactLoginHeading {
            get {
                return ResourceManager.GetString("YammerContactLoginHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a Message to our Yammer Group using Email:.
        /// </summary>
        public static string YammerEmailHeading {
            get {
                return ResourceManager.GetString("YammerEmailHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
